### ISSUE TITLE
Auto completing doesn't work

### ISSUE THREAD

**Issue by Pablete1234** [CardinalDevelopment/EllyCommand#2]
![image](https://cloud.githubusercontent.com/assets/11789291/17920594/c47e7426-69d5-11e6-9b42-004ad73898b7.png)

It doesn't get to fire the getSuggestions() method on the provider

**Comment by connorjayr** [comment]
What version are you using?

**Comment by Pablete1234** [comment]
2.0.4

**Comment by connorjayr** [comment]
Update to 2.1.0

**Comment by Pablete1234** [comment]
I would if i had push perms on cardinal repo...

**Comment by connorjayr** [comment]
That is irrelevant. Did it fix the problem locally?

**Comment by Pablete1234** [comment]
Problem isn't fixed, same error message

**Comment by connorjayr** [comment]
Which command is this for?
